version: '3.4'

services:
  smarthome.portal:
    image: ${DOCKER_REGISTRY-}smarthomeportal
    build:
      context: .
      dockerfile: SmartHome.Portal/Dockerfile
      args:
        GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
        PROJECT_ID: $PROJECT_ID
        IOT_CORE_REGION: $IOT_CORE_REGION
        IOT_CORE_REGISTRY_ID: $IOT_CORE_REGISTRY_ID
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
      - PROJECT_ID=$PROJECT_ID
      - IOT_CORE_REGION
      - IOT_CORE_REGISTRY_ID
